name: Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run:
        yarn --frozen-lockfile
    - name: setup git
      run: |
        git config --global user.email "hello@rachelwonghw.com"
        git config --global user.name "Rachel Wong"
        git remote set-url origin https://${{secrets.DEPLOY_TOKEN}}@github.com/rachelwonghw/rachelwonghw.github.io.git
    - name: deploy
      run:
        yarn run deploy
